# Generated by Django 4.0.4 on 2022-11-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuff', models.CharField(max_length=100)),
                ('ddl', models.CharField(max_length=100)),
                ('box', models.IntegerField(choices=[(1, 1), (2, 2)], default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
